@startuml ValidationAppendDelete
title Validation & Append

skinparam component {
  BorderColor black
  BackgroundColor white
  FontSize 12
}

' Define the object instances
object "EntryList (before)" as EL_B
object "MealEntry" as MA {
  [MILK] 150ml (dd/MM/yy HH:mm)
}

object "WorkoutEntry" as MB {
    [Workout] yoga (30 mins, feel 3/5) (dd/MM/yy HH:mm)
}
object "MilkEntry" as MC {
  [MILK] 150ml (dd/MM/yy HH:mm)
}

object "EntryList (after)" as EL_A {

}
object "MealEntry" as MD {
    [Meal] breakfast (500 kcal) (dd/MM/yy HH:mm)
}

object "MilkEntry" as ME {
    [MILK] 150ml (dd/MM/yy HH:mm)
}
' 1. Show the action (Append)
EL_B -right-> EL_A : delete WorkoutEntry

' 2. Show the containment/link relationship
'    The EntryList (after) contains the new MilkEntry
EL_A o-- ME : contains
EL_A o-- MD : contains

EL_B o-- MB : contains
EL_B o-- MA : contains
EL_B o-- MC : contains

@enduml