@startuml ValidationAppendDelete
title Initial State (before delete)

skinparam component {
  BorderColor black
  BackgroundColor white
  FontSize 12
}

' Define the object instances
object "EntryList (before)" as EL_B
object "MealEntry" as MA {
  [MILK] 150ml (dd/MM/yy HH:mm)
}

object "WorkoutEntry" as MB {
  [MILK] 150ml (dd/MM/yy HH:mm)
}
object "MilkEntry" as MC {
  [MILK] 150ml (dd/MM/yy HH:mm)
}

EL_B o-- MB : contains
EL_B o-- MA : contains
EL_B o-- MC : contains

@enduml